version: '3.8'

services:
  populate_db:
    volumes:
      - type: bind
        source: ../
        target: /wikiguesser
    build:
        dockerfile: ../wiki_random/Dockerfile
    command: bash -c "sleep 15 && cd wikiguesser/wiki_random/ && bash diesel_setup.sh && bash populate_database.sh"
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:wikiguesser@localhost:5432/articles}"
    depends_on:
      - postgres
    network_mode: host

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "wikiguesser"
      PGPASSWORD: "wikiguesser"
    ports:
      - 5432
    network_mode: host
